#
# Copyright (c) 2016 Juniper Networks, Inc. All rights reserved.
#

Import('BuildEnv')
env = BuildEnv.Clone()

subdirs = [
            'tungsten_cli',
            'tungsten_analytics_cli',
            'tungsten_config_cli',
            'tungsten_control_cli',
            'tungsten_vrouter_cli',
          ]

for dir in subdirs:
    env.SConscript(dir + '/SConscript',
                         exports='BuildEnv')
