# -*- mode: python; -*-

#
# Copyright (c) 2015 Juniper Networks, Inc. All rights reserved.
#

Import('AnalyticsEnv')
DatabaseEnv = AnalyticsEnv.Clone()

utils_scripts = [
    'tungsten-cassandra-status.py',
    'tungsten-cassandra-repair.py',
    'tungsten-cassandra-check-start',
]

for utils in utils_scripts:
    DatabaseEnv.Alias('install', DatabaseEnv.Install(DatabaseEnv['INSTALL_EXAMPLE'], utils))
