#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

import os

Import('BuildEnv')
env = BuildEnv.Clone()

sources = [
    'setup.py',
    'tungsten_vrouter_provisioning/__init__.py',
    'tungsten_vrouter_provisioning/setup.py',
    'tungsten_vrouter_provisioning/cmdparser.py',
    'tungsten_vrouter_provisioning/base.py',
    'tungsten_vrouter_provisioning/common.py',
    'tungsten_vrouter_provisioning/network.py',
    'tungsten_vrouter_provisioning/toragent/__init__.py',
    'tungsten_vrouter_provisioning/toragent/setup.py',
    'tungsten_vrouter_provisioning/toragent/cleanup.py',
    'tungsten_vrouter_provisioning/toragent/templates/__init__.py',
    'tungsten_vrouter_provisioning/toragent/templates/tor_agent_conf.py',
    'tungsten_vrouter_provisioning/toragent/templates/tor_agent_ini.py',
    'tungsten_vrouter_provisioning/toragent/templates/tor_agent_service.py',
    ]

cd_cmd = 'cd ' + Dir('.').path + ' && '
sdist_gen = env.Command('dist/tungsten-vrouter-provisioning-1.0.tar.gz',
                        sources,
                        cd_cmd + 'python setup.py sdist')

env.Alias('controller/src/vnsw/tungsten_vrouter_provisioning:sdist', sdist_gen)

if 'install' in BUILD_TARGETS:
    install_cmd = env.Command(None, sources,
                              cd_cmd + 'python setup.py install %s' %
                              env['PYTHON_INSTALL_OPT'])
    env.Alias('install', install_cmd)

# Local Variables:
# mode: python
# End:
