#
# Copyright (c) 2016 Juniper Networks, Inc. All rights reserved.
#

"""
This helper script is used to dynamically update configs to named.
o For backward compatibility we read the named configurable
   params from tungsten-dns.conf and build tungsten-named-base.conf
o Alternatively user can create/update tungsten-name-base.conf
   for configuring named params
o tungsten-named.conf will be generated by dnsd which will
   contain views/zones stanzas
o tungsten-named-base.conf will be merged with tungsten-named.conf
   by the script and config applied to named
"""

import sys
import os
import subprocess
import ConfigParser


def parse_tungsten_dns_conf():

    named_defaults = {
        'named_config_file': 'tungsten-named.conf',
        'named_config_directory': '/etc/tungsten/dns',
        'named_log_file': '/var/log/tungsten/tungsten-named.log',
        'rndc_config_file': 'tungsten-rndc.conf',
        'rndc_secret': 'xvysmOR8lnUQRBcunkC6vg==',
        'named_max_cache_size': '32M',
        'named_max_retransmissions': '12',
        'named_retransmission_interval': '1000',
    }

    # remove preceeding spaces from tungsten-dns.conf
    # and save it in tungsten-dns-temp.conf
    subprocess.call(["sed -e 's/^[ \t]*//g' < /etc/tungsten/tungsten-dns.conf \
                                            > /etc/tungsten/dns/tungsten-dns-temp.conf"], shell=True)
    # remove comments preceeding with #
    subprocess.call(["sed -i 's/[;#].*$//g' /etc/tungsten/dns/tungsten-dns-temp.conf"], shell=True)

    # parse tungsten-dns.conf
    dns_config = ConfigParser.SafeConfigParser()
    dns_config.read('/etc/tungsten/dns/tungsten-dns-temp.conf')

    # remove the temp file
    os.remove("/etc/tungsten/dns/tungsten-dns-temp.conf")

    # update defaults
    named_defaults.update(dict(dns_config.items("DEFAULT")))

    # create tungsten-named-base.conf
    file_named_base_conf=open('/etc/tungsten/dns/tungsten-named-base.conf', 'w+')

    # build tungsten-named-base.conf

    # build options {} stanza
    file_named_base_conf.write('options {\n')
    file_named_base_conf.write('    directory "'+ named_defaults['named_config_directory'] + '";\n')
    file_named_base_conf.write('    managed-keys-directory "'+ named_defaults['named_config_directory'] + '";\n')
    file_named_base_conf.write('    empty-zones-enable no;\n')
    file_named_base_conf.write('    pid-file "/etc/tungsten/dns/tungsten-named.pid";\n')
    file_named_base_conf.write('    session-keyfile "/etc/tungsten/dns/session.key";\n')
    file_named_base_conf.write('    listen-on port 53 { any; };\n')
    file_named_base_conf.write('    allow-query { any; };\n')
    file_named_base_conf.write('    allow-recursion { any; };\n')
    file_named_base_conf.write('    allow-query-cache { any; };\n')
    file_named_base_conf.write('    max-cache-size '+ named_defaults['named_max_cache_size'] + ';\n')
    file_named_base_conf.write('};\n\n')

    # build rndc-key {} stanza
    file_named_base_conf.write('key "rndc-key" {\n')
    file_named_base_conf.write('   algorithm hmac-md5;\n')
    file_named_base_conf.write('   secret "' + named_defaults['rndc_secret'] + '";\n')
    file_named_base_conf.write('};\n\n')

    #build controls {} stanza
    file_named_base_conf.write('controls {\n')
    file_named_base_conf.write('    inet 127.0.0.1 port 8094 \n')
    file_named_base_conf.write('    allow { 127.0.0.1; }  keys { "rndc-key"; };\n')
    file_named_base_conf.write('};\n\n')

    #build logging {} stanza
    file_named_base_conf.write('logging {\n')
    file_named_base_conf.write('    channel debug_log {\n')
    file_named_base_conf.write('        file "'+ named_defaults['named_log_file'] + '" versions 5 size 5m;\n')
    file_named_base_conf.write('        severity debug;\n')
    file_named_base_conf.write('        print-time yes;\n')
    file_named_base_conf.write('        print-severity yes;\n')
    file_named_base_conf.write('        print-category yes;\n')
    file_named_base_conf.write('    };\n')
    file_named_base_conf.write('    category default {\n')
    file_named_base_conf.write('        debug_log;\n')
    file_named_base_conf.write('    };\n')
    file_named_base_conf.write('    category queries {\n')
    file_named_base_conf.write('        debug_log;\n')
    file_named_base_conf.write('    };\n')
    file_named_base_conf.write('};\n\n')

    file_named_base_conf.close()

# end parse_tungsten_dns_conf

def main():
    if not os.path.exists('/etc/tungsten/dns/tungsten-named-base.conf'):
        # parse tungsten-dns.conf and build tungsten-named-base.conf
        parse_tungsten_dns_conf()

    # open tungsten-named-base.conf and read the base configs
    file1 = open('/etc/tungsten/dns/tungsten-named-base.conf', 'r')
    file1_lines = file1.readlines()
    file1.close()

    # open tungsten-named.conf and remove configurable stanzas
    # options{} key{} controls{} logging {}
    count = 0
    file2 = open('/etc/tungsten/dns/tungsten-named.conf', 'r')
    lines = file2.readlines()
    for i, line in enumerate(lines[:]):
        if line.startswith('view'):
            break
        else:
           count = count + 1
    file2.close()

    # delete all lines before the view stanza {}
    del lines[0:count]

    # open tungsten-named.conf
    file3 = open('/etc/tungsten/dns/tungsten-named.conf', 'w')
    file3.truncate()
    file3.write("/* Build from tungsten-named-base.conf */\n")
    file3.writelines(file1_lines)
    file3.write("/* Build from tungsten-named.conf */\n")
    file3.writelines(lines)
    file3.close()

    # apply config
    os.system('/usr/bin/tungsten-rndc -c /etc/tungsten/dns/tungsten-rndc.conf reconfig')
#end main

if __name__ == "__main__":
    main()
